### ISSUE TITLE
Bug in experimental convector support

### ISSUE THREAD

**Issue by danielgospodinow** [qbaware/homeassistant-eldom#25]
This is some kind of a bug that bubbled up during volunteer testing of the experimental convertor support by @maslyankov.  

```text
Logger: homeassistant.helpers.entity_platform
Source: helpers/entity_platform.py:420
First occurred: 22:53:53 (6 occurrences)
Last logged: 22:54:02

eldom raises exception ConfigEntryNotReady in forwarded platform sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
eldom raises exception ConfigEntryNotReady in forwarded platform switch; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
eldom raises exception ConfigEntryNotReady in forwarded platform water_heater; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups

This error originated from a custom integration.

Logger: custom_components.eldom.coordinator
Source: helpers/update_coordinator.py:379
integration: Eldom (documentation, issues)
First occurred: 22:53:53 (6 occurrences)
Last logged: 22:54:02

Unexpected error fetching eldom data
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
 self.data = await self._async_update_data()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/docker/config/custom_components/eldom/coordinator.py", line 38, in _async_update_data
 devices = await self.api.get_devices()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.13/site-packages/eldom/client.py", line 93, in get_devices
 response_json = json.loads(await response.text())
 File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
 return _default_decoder.decode(s)
 ~~~~~~~~~~~~~~~~~~~~~~~^^^
 File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
 raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by danielgospodinow** [comment]
Fixed with https://github.com/qbaware/homeassistant-eldom/releases/tag/3.1.1.
